# Generated by Django 5.0.6 on 2026-08-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_face_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voice_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
